version: "3"
services:
  api:
    build: ./api
    ports:
      - "4000:4000"
    volumes:
      - ./api:/app
      - ./views:/app/views
      - ./public:/app/public
      - ./node_modules:/app/node_modules
    depends_on:
      - app
  app:
    build: ./app
    ports:
      - "3000:3000"
    volumes:
      - ./app:/app
      - ./views:/app/views
      - ./public:/app/public
      - ./node_modules:/app/node_modules
