version: '3'
services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile-api
    ports:
      - "4000:4000"
  application:
    build:
      context: ./application
      dockerfile: Dockerfile-application
    ports:
      - "3000:3000"
