version: '3'
services:
  app1:
    build:
      context: .
      dockerfile: Dockerfile.app1
    ports:
      - "4000:4000"
  app2:
    build:
      context: .
      dockerfile: Dockerfile.app2
    ports:
      - "3000:3000"
